spring:
  datasource:
    url: ${MYSQL_DB_ENDPOINT}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:postgresql://${DB_ENDPOINT}:5432/postgres?useSSL=false&serverTimezone=Asia/Seoul
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          exception-handling: ignore
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: quitmate
#spring:
#  datasource:
#    url: jdbc:mysql://${DB_ENDPOINT}:3306/quitmate?useSSL=false&serverTimezone=Asia/Seoul
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#        jdbc:
#          exception-handling: ignore

    logging:
      level:
        p6spy: info

      decorator:
        datasource:
          p6spy:
            enable-logging: true

jwt:
  secret-key: ${JWT_SECRET_KEY}

aes:
  key-value: ${AES_KEY}

logging:
  config: classpath:logback/logback-config.xml

oracle:
  cloud:
    region: ap-chuncheon-1
  name-space-name: ${NAMESPACE_NAME}
  user:
    bucket-name: ${USER_BUCKET_NAME_DEV}
  challenge:
    bucket-name: ${CHALLENGE_BUCKET_NAME_DEV}
