name: ğŸš€ ë°°í¬

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MYSQL_DB_ENDPOINT: ${{ secrets.MYSQL_DB_ENDPOINT }}
      MYSQL_DB_USERNAME: ${{ secrets.MYSQL_DB_USERNAME }}
      MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: ğŸ”¨ JDK 17 ì„¸íŒ…
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ”¨ gradlew ì‹¤í–‰ ê¶Œí•œ ì„¤ì •
        run: chmod +x gradlew

      - name: ğŸ”¨ Gradle ìºì‹œ ì„¤ì •
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: ğŸ”¨ Gradle ë¹Œë“œ
        run: ./gradlew build --parallel

      - name: ğŸ“¦ jar, ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ ë³µì‚¬
        run: |
          mkdir -p before-deploy-admin
          cp ./build/libs/*.jar ./before-deploy-admin/
          cp -r ./scripts/dev/ ./before-deploy-admin/scripts/

      - name: ğŸ—œï¸ ë°°í¬ íŒ¨í‚¤ì§€ ìƒì„±
        run: zip -r -qq ./deploy.zip ./before-deploy-admin/

      - name: ğŸ”‘ SSH í‚¤ ì„¤ì •
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

      - name: ğŸ”‘ Ubuntu í˜¸ìŠ¤íŠ¸ ì¶”ê°€
        run: |
          ssh-keyscan -H ${{ secrets.DEV_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: ğŸš€ ì„œë²„ì— íŒŒì¼ ì—…ë¡œë“œ
        run: |
          scp ./deploy.zip ubuntu@${{ secrets.DEV_SERVER_IP }}:/home/ubuntu/deploy.zip
          ssh ubuntu@${{ secrets.DEV_SERVER_IP }} "
            unzip -o /home/ubuntu/deploy.zip -d /home/ubuntu &&
            rm -rf /home/ubuntu/admin-app/* &&
            mv /home/ubuntu/before-deploy-admin/* /home/ubuntu/admin-app/ &&
            chmod +x /home/ubuntu/admin-app/scripts/*.sh"

      - name: ğŸ¯ Ubuntu ì„œë²„ì—ì„œ ë°°í¬ ì‹¤í–‰
        run: |
          ssh ubuntu@${{ secrets.DEV_SERVER_IP }} "/home/ubuntu/admin-app/scripts/run_new_was.sh"

      - name: ğŸ¯ Ubuntu ì„œë²„ì—ì„œ Health Checking
        run: |
          ssh ubuntu@${{ secrets.DEV_SERVER_IP }} "/home/ubuntu/admin-app/scripts/health.sh"

#      - name: ğŸ¯ Ubuntu ì„œë²„ì—ì„œ Blue/Green Switching
#        run: |
#          ssh ubuntu@${{ secrets.DEV_SERVER_IP }} "/home/ubuntu/admin-app/scripts/switch.sh"

      - name: ğŸ§¹ ì„ì‹œ íŒŒì¼ ì •ë¦¬
        run: |
          ssh ubuntu@${{ secrets.DEV_SERVER_IP }} "
            rm -rf /home/ubuntu/deploy.zip /home/ubuntu/before-deploy-admin"
